-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jan 02, 2024 at 09:00 AM
-- Server version: 10.6.16-MariaDB-cll-lve
-- PHP Version: 8.1.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `weba3991_ntaafuo`
--

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `list_rooms`
--

CREATE TABLE `list_rooms` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) NOT NULL,
  `imageData1` varchar(255) NOT NULL,
  `imageData2` varchar(255) NOT NULL,
  `imageData3` varchar(255) NOT NULL,
  `rent` int(11) NOT NULL,
  `terms` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `town` varchar(255) NOT NULL,
  `referal` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `list_rooms`
--

INSERT INTO `list_rooms` (`id`, `email`, `imageData1`, `imageData2`, `imageData3`, `rent`, `terms`, `city`, `town`, `referal`, `created_at`, `updated_at`) VALUES
(48, 'Kwame@gmail.com', 'roomPictures/HXUXPLN0290M575uasIceJQgrECSRGMAf3bzvl4R.jpg', 'roomPictures/gTn3V7WtkmqN2fslIkIaCxMNAguGH1ElbJdxC7lV.jpg', 'roomPictures/qUvA6bKdHwzuRL8v7nvzDWLzILL9KjpSDykreidU.jpg', 1000, '2 years', 'Accra', 'Airport Residential Area', 'autogenerated', '2023-10-17 11:39:14', '2023-10-17 11:39:14'),
(49, 'Ekow@gmail.com', 'roomPictures/YaBWbAmwa4h4V7CdN957G9gA8CBkavvXR1ZUGtm0.jpg', 'roomPictures/KWRGQycWs6OaoTq3xJ0D53lzK2aNwfk89Ap3Z7uN.jpg', 'roomPictures/TPbqeSOCm1Dec8bZQiJSJIJ6d9veLkn7McnkxBol.jpg', 1000, '2 years', 'Accra', 'Spintex', 'autogenerated', '2023-10-17 11:46:30', '2023-10-17 11:46:30'),
(50, 'haiderhamdani1996@gmail.com', 'roomPictures/rRsa6rYKtL6OBJM9PW2nPg7ZulroIfiPOGWu6Msl.jpg', 'roomPictures/Obi1h7FCIj39wEZCbDlIcBmart2fQhukf5YF1V0r.jpg', 'roomPictures/SwyDgJMBtwZpr9vKaDrlUgmTlEN39tVtxM5WH6or.jpg', 1000, '1 year', 'Accra', 'Osu', 'autogenerated', '2023-10-17 11:55:18', '2023-10-17 11:55:18'),
(51, 'Adisa@gmail.com', 'roomPictures/qpmiydxgducAB6ctAEtQsa3k5AigL5pIb9Qvnxfm.jpg', 'roomPictures/Pbo1KJFlnQUSShSexBPN1t6HDpcPXmYxn1hkHDGq.jpg', 'roomPictures/3xdgRj3UjYmqlRgJXBpcZWug4BPG9STgxW4sKdkD.jpg', 2000, '1 year', 'Accra', 'Cantoment', 'autogenerated', '2023-10-17 13:39:05', '2023-10-17 13:39:05'),
(52, 'Jelani@gmail.com', 'roomPictures/XOk2TuoWbMiRrImt3bByPXjfOzFkKwiiPkHyNv4q.jpg', 'roomPictures/nYiYvCOaLXjzTGXGrBiCMoDpL4rIFFosylq3dw9q.jpg', 'roomPictures/fAiHdFLdSEf39DSbjQtN462NjBZ8rgX3pjCUqQON.jpg', 3000, '1 year', 'Accra', 'Madina', 'autogenerated', '2023-10-17 13:42:34', '2023-10-17 13:42:34'),
(53, 'Abidemi@gmail.com', 'roomPictures/0fZ48J6poVFaA5HzOpU843Yyufizh6vo2ntQA948.jpg', 'roomPictures/xVvdXlRgLLu7A2Y0GILfUscGREHEXgYbrJ4aAD13.jpg', 'roomPictures/9RZGBOsuSSXjhACQOwOsaeyAy4rH1TjQfK2E1qfH.jpg', 2000, '1 year', 'Kumasi', 'Kentinkrono', 'autogenerated', '2023-10-17 13:46:44', '2023-10-17 13:46:44'),
(55, 'Yawo@gmail.com', 'roomPictures/EoeoK7ArhDaPglW2o8T6oU6Bosod1wYTXlhIuHHi.jpg', 'roomPictures/UqTQCbiI6n5iqaSZraZeJYSpwJ0S13i7NTYssauW.jpg', 'roomPictures/X6sKRHCqQ3XyWmPfGOC1mpIFRXVyy3il4Z9IiTCC.jpg', 1000, '1 year', 'Kumasi', 'Ayigya', 'autogenerated', '2023-10-19 08:56:21', '2023-10-19 08:56:21'),
(56, 'justofosu@gmail.com', 'roomPictures/lNNEbFkPzpL6kYuhYhIziKszpVPGoTPOkd7h7DrD.png', 'roomPictures/kmHqd7bO63ypkl41VdRBnPNNeFRvQGIc6DCajYd2.jpg', 'roomPictures/OfNTCKrC26016PRTK3Gvm2teRyd2mNZXxDsMXDpu.png', 300, '1 year', 'Accra', 'Cantoment', 'autogenerated', '2023-12-04 18:20:55', '2023-12-04 18:20:55'),
(57, 'haiderhamdani95@gmail.com', 'roomPictures/2QhmfT7gLzAW4vPPsyZCdqz7p5zgeiiRok4Y3856.jpg', 'roomPictures/leWRISVNQ2vaStSmOii6Bk5fUXjusmnLYXBhmId7.jpg', 'roomPictures/NgMPVtcAvR42JgosLWVXf8Wvttb0m2gA9uwhceKA.jpg', 21321, '1 year', 'Kumasi', 'Atasemanso', 'autogenerated', '2023-12-04 18:33:49', '2023-12-04 18:33:49');

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(16, '2023_08_15_203716_create_profiles_table', 2),
(17, '2023_08_23_161743_create_list_rooms_table', 2),
(18, '2023_09_20_165753_add_new_column_to_profiles_table', 3),
(20, '2023_09_27_124047_create_payments_table', 4);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `password_resets`
--

INSERT INTO `password_resets` (`email`, `token`, `created_at`) VALUES
('Yaa@gmail.com', '$2y$10$RTMoqI60Eoo8ar7.ly0Xk.2sGCZAu9FO836mrkknnt6A0o7Z.mjaC', '2023-09-23 18:20:52'),
('rosefunerals@outlook.com', '$2y$10$u9J62/a3m7BXtgLTSb.w.udRFnTPZgBLJaoLoh8cjXrP80vOi28XG', '2023-11-17 03:55:33');

-- --------------------------------------------------------

--
-- Table structure for table `payments`
--

CREATE TABLE `payments` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) NOT NULL,
  `orderiD` varchar(255) NOT NULL,
  `amount` int(11) NOT NULL,
  `currency` varchar(255) NOT NULL,
  `reference` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `payments`
--

INSERT INTO `payments` (`id`, `email`, `orderiD`, `amount`, `currency`, `reference`, `created_at`, `updated_at`) VALUES
(4, 'pp@gmail.com', '142244184', 1000, 'GHS', 'IMLPYqj4JrF58T4IgQvFlYGj7', '2023-09-27 17:49:13', '2023-09-27 17:49:13'),
(5, 'haiderhamdani1996@gmail.com', '142080430', 1000, 'GHS', 'h0yUjk3QhisS15Gov6WQRuNlb', '2023-09-28 10:35:27', '2023-09-28 10:35:27'),
(6, 'kwame@gmail.com', '144574653', 1000, 'GHS', 'kXJUPJtCAQDZwAdHlIFz8hB9w', '2023-10-17 11:39:52', '2023-10-17 11:39:52'),
(7, 'ekow@gmail.com', '144575607', 1000, 'GHS', 'afdkB6RHWhxvSdOywmBBWDh0U', '2023-10-17 11:46:54', '2023-10-17 11:46:54'),
(8, 'haiderhamdani1996@gmail.com', '142080430', 1000, 'GHS', 'tVMEAXw1Hbxzh9SW0MTe1mjOB', '2023-10-17 11:55:54', '2023-10-17 11:55:54'),
(9, 'adisa@gmail.com', '144590239', 1000, 'GHS', '4Ykhhxyd6URVvG6T6Q9bL20ka', '2023-10-17 13:39:41', '2023-10-17 13:39:41'),
(10, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:47:57', '2023-10-17 13:47:57'),
(11, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:47:58', '2023-10-17 13:47:58'),
(12, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:47:59', '2023-10-17 13:47:59'),
(13, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:00', '2023-10-17 13:48:00'),
(14, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:02', '2023-10-17 13:48:02'),
(15, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:03', '2023-10-17 13:48:03'),
(16, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:04', '2023-10-17 13:48:04'),
(17, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:05', '2023-10-17 13:48:05'),
(18, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:07', '2023-10-17 13:48:07'),
(19, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:08', '2023-10-17 13:48:08'),
(20, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:09', '2023-10-17 13:48:09'),
(21, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:10', '2023-10-17 13:48:10'),
(22, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:12', '2023-10-17 13:48:12'),
(23, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:13', '2023-10-17 13:48:13'),
(24, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:15', '2023-10-17 13:48:15'),
(25, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:17', '2023-10-17 13:48:17'),
(26, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:18', '2023-10-17 13:48:18'),
(27, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:21', '2023-10-17 13:48:21'),
(28, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:22', '2023-10-17 13:48:22'),
(29, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:22', '2023-10-17 13:48:22'),
(30, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:23', '2023-10-17 13:48:23'),
(31, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:24', '2023-10-17 13:48:24'),
(32, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:24', '2023-10-17 13:48:24'),
(33, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:25', '2023-10-17 13:48:25'),
(34, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:27', '2023-10-17 13:48:27'),
(35, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:28', '2023-10-17 13:48:28'),
(36, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:29', '2023-10-17 13:48:29'),
(37, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:30', '2023-10-17 13:48:30'),
(38, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:32', '2023-10-17 13:48:32'),
(39, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:33', '2023-10-17 13:48:33'),
(40, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:34', '2023-10-17 13:48:34'),
(41, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:35', '2023-10-17 13:48:35'),
(42, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:36', '2023-10-17 13:48:36'),
(43, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:38', '2023-10-17 13:48:38'),
(44, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:39', '2023-10-17 13:48:39'),
(45, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:40', '2023-10-17 13:48:40'),
(46, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:41', '2023-10-17 13:48:41'),
(47, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:43', '2023-10-17 13:48:43'),
(48, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:44', '2023-10-17 13:48:44'),
(49, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:45', '2023-10-17 13:48:45'),
(50, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:46', '2023-10-17 13:48:46'),
(51, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:48', '2023-10-17 13:48:48'),
(52, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:49', '2023-10-17 13:48:49'),
(53, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:50', '2023-10-17 13:48:50'),
(54, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:51', '2023-10-17 13:48:51'),
(55, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:53', '2023-10-17 13:48:53'),
(56, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:54', '2023-10-17 13:48:54'),
(57, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:55', '2023-10-17 13:48:55'),
(58, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:56', '2023-10-17 13:48:56'),
(59, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:48:58', '2023-10-17 13:48:58'),
(60, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:00', '2023-10-17 13:49:00'),
(61, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:02', '2023-10-17 13:49:02'),
(62, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:03', '2023-10-17 13:49:03'),
(63, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:03', '2023-10-17 13:49:03'),
(64, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:04', '2023-10-17 13:49:04'),
(65, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:05', '2023-10-17 13:49:05'),
(66, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:06', '2023-10-17 13:49:06'),
(67, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:08', '2023-10-17 13:49:08'),
(68, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:09', '2023-10-17 13:49:09'),
(69, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:10', '2023-10-17 13:49:10'),
(70, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:11', '2023-10-17 13:49:11'),
(71, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:13', '2023-10-17 13:49:13'),
(72, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:14', '2023-10-17 13:49:14'),
(73, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:15', '2023-10-17 13:49:15'),
(74, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:17', '2023-10-17 13:49:17'),
(75, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:18', '2023-10-17 13:49:18'),
(76, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:19', '2023-10-17 13:49:19'),
(77, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:20', '2023-10-17 13:49:20'),
(78, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:21', '2023-10-17 13:49:21'),
(79, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:23', '2023-10-17 13:49:23'),
(80, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:24', '2023-10-17 13:49:24'),
(81, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:25', '2023-10-17 13:49:25'),
(82, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:26', '2023-10-17 13:49:26'),
(83, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:28', '2023-10-17 13:49:28'),
(84, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:29', '2023-10-17 13:49:29'),
(85, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:30', '2023-10-17 13:49:30'),
(86, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:32', '2023-10-17 13:49:32'),
(87, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:33', '2023-10-17 13:49:33'),
(88, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:34', '2023-10-17 13:49:34'),
(89, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:35', '2023-10-17 13:49:35'),
(90, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:37', '2023-10-17 13:49:37'),
(91, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:38', '2023-10-17 13:49:38'),
(92, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:40', '2023-10-17 13:49:40'),
(93, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:40', '2023-10-17 13:49:40'),
(94, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:42', '2023-10-17 13:49:42'),
(95, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:43', '2023-10-17 13:49:43'),
(96, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:44', '2023-10-17 13:49:44'),
(97, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:45', '2023-10-17 13:49:45'),
(98, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:47', '2023-10-17 13:49:47'),
(99, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:48', '2023-10-17 13:49:48'),
(100, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:49', '2023-10-17 13:49:49'),
(101, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:50', '2023-10-17 13:49:50'),
(102, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:52', '2023-10-17 13:49:52'),
(103, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:53', '2023-10-17 13:49:53'),
(104, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:54', '2023-10-17 13:49:54'),
(105, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:55', '2023-10-17 13:49:55'),
(106, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:57', '2023-10-17 13:49:57'),
(107, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:58', '2023-10-17 13:49:58'),
(108, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:49:59', '2023-10-17 13:49:59'),
(109, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:01', '2023-10-17 13:50:01'),
(110, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:02', '2023-10-17 13:50:02'),
(111, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:04', '2023-10-17 13:50:04'),
(112, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:04', '2023-10-17 13:50:04'),
(113, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:06', '2023-10-17 13:50:06'),
(114, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:07', '2023-10-17 13:50:07'),
(115, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:08', '2023-10-17 13:50:08'),
(116, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:09', '2023-10-17 13:50:09'),
(117, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:11', '2023-10-17 13:50:11'),
(118, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:12', '2023-10-17 13:50:12'),
(119, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:13', '2023-10-17 13:50:13'),
(120, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:14', '2023-10-17 13:50:14'),
(121, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:16', '2023-10-17 13:50:16'),
(122, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:17', '2023-10-17 13:50:17'),
(123, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:18', '2023-10-17 13:50:18'),
(124, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:19', '2023-10-17 13:50:19'),
(125, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:20', '2023-10-17 13:50:20'),
(126, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:22', '2023-10-17 13:50:22'),
(127, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:23', '2023-10-17 13:50:23'),
(128, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:24', '2023-10-17 13:50:24'),
(129, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:25', '2023-10-17 13:50:25'),
(130, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:27', '2023-10-17 13:50:27'),
(131, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:28', '2023-10-17 13:50:28'),
(132, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:29', '2023-10-17 13:50:29'),
(133, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:30', '2023-10-17 13:50:30'),
(134, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:32', '2023-10-17 13:50:32'),
(135, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:33', '2023-10-17 13:50:33'),
(136, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:34', '2023-10-17 13:50:34'),
(137, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:35', '2023-10-17 13:50:35'),
(138, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:37', '2023-10-17 13:50:37'),
(139, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:38', '2023-10-17 13:50:38'),
(140, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:39', '2023-10-17 13:50:39'),
(141, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:40', '2023-10-17 13:50:40'),
(142, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:41', '2023-10-17 13:50:41'),
(143, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:43', '2023-10-17 13:50:43'),
(144, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:44', '2023-10-17 13:50:44'),
(145, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:45', '2023-10-17 13:50:45'),
(146, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:47', '2023-10-17 13:50:47'),
(147, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:48', '2023-10-17 13:50:48'),
(148, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:49', '2023-10-17 13:50:49'),
(149, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:50', '2023-10-17 13:50:50'),
(150, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:51', '2023-10-17 13:50:51'),
(151, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:53', '2023-10-17 13:50:53'),
(152, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:54', '2023-10-17 13:50:54'),
(153, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:55', '2023-10-17 13:50:55'),
(154, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:56', '2023-10-17 13:50:56'),
(155, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:50:58', '2023-10-17 13:50:58'),
(156, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:01', '2023-10-17 13:51:01'),
(157, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:25', '2023-10-17 13:51:25'),
(158, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:26', '2023-10-17 13:51:26'),
(159, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:27', '2023-10-17 13:51:27'),
(160, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:28', '2023-10-17 13:51:28'),
(161, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:29', '2023-10-17 13:51:29'),
(162, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:33', '2023-10-17 13:51:33'),
(163, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:35', '2023-10-17 13:51:35'),
(164, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:37', '2023-10-17 13:51:37'),
(165, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:38', '2023-10-17 13:51:38'),
(166, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:39', '2023-10-17 13:51:39'),
(167, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:40', '2023-10-17 13:51:40'),
(168, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:42', '2023-10-17 13:51:42'),
(169, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:43', '2023-10-17 13:51:43'),
(170, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:44', '2023-10-17 13:51:44'),
(171, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:45', '2023-10-17 13:51:45'),
(172, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:47', '2023-10-17 13:51:47'),
(173, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:48', '2023-10-17 13:51:48'),
(174, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:49', '2023-10-17 13:51:49'),
(175, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:50', '2023-10-17 13:51:50'),
(176, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:52', '2023-10-17 13:51:52'),
(177, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:53', '2023-10-17 13:51:53'),
(178, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:54', '2023-10-17 13:51:54'),
(179, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:56', '2023-10-17 13:51:56'),
(180, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:57', '2023-10-17 13:51:57'),
(181, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:58', '2023-10-17 13:51:58'),
(182, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:51:59', '2023-10-17 13:51:59'),
(183, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:01', '2023-10-17 13:52:01'),
(184, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:02', '2023-10-17 13:52:02'),
(185, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:03', '2023-10-17 13:52:03'),
(186, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:05', '2023-10-17 13:52:05'),
(187, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:06', '2023-10-17 13:52:06'),
(188, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:07', '2023-10-17 13:52:07'),
(189, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:08', '2023-10-17 13:52:08'),
(190, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:10', '2023-10-17 13:52:10'),
(191, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:11', '2023-10-17 13:52:11'),
(192, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:12', '2023-10-17 13:52:12'),
(193, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:14', '2023-10-17 13:52:14'),
(194, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:15', '2023-10-17 13:52:15'),
(195, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:16', '2023-10-17 13:52:16'),
(196, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:18', '2023-10-17 13:52:18'),
(197, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:19', '2023-10-17 13:52:19'),
(198, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:20', '2023-10-17 13:52:20'),
(199, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:21', '2023-10-17 13:52:21'),
(200, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:23', '2023-10-17 13:52:23'),
(201, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:24', '2023-10-17 13:52:24'),
(202, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:25', '2023-10-17 13:52:25'),
(203, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:27', '2023-10-17 13:52:27'),
(204, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:28', '2023-10-17 13:52:28'),
(205, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:30', '2023-10-17 13:52:30'),
(206, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:31', '2023-10-17 13:52:31'),
(207, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:32', '2023-10-17 13:52:32'),
(208, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:33', '2023-10-17 13:52:33'),
(209, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:34', '2023-10-17 13:52:34'),
(210, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:36', '2023-10-17 13:52:36'),
(211, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:37', '2023-10-17 13:52:37'),
(212, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:38', '2023-10-17 13:52:38'),
(213, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:40', '2023-10-17 13:52:40'),
(214, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:41', '2023-10-17 13:52:41'),
(215, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:42', '2023-10-17 13:52:42'),
(216, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:43', '2023-10-17 13:52:43'),
(217, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:45', '2023-10-17 13:52:45'),
(218, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:46', '2023-10-17 13:52:46'),
(219, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:47', '2023-10-17 13:52:47'),
(220, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:49', '2023-10-17 13:52:49'),
(221, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:50', '2023-10-17 13:52:50'),
(222, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:51', '2023-10-17 13:52:51'),
(223, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:53', '2023-10-17 13:52:53'),
(224, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:54', '2023-10-17 13:52:54'),
(225, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:55', '2023-10-17 13:52:55'),
(226, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:56', '2023-10-17 13:52:56'),
(227, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:52:58', '2023-10-17 13:52:58'),
(228, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:00', '2023-10-17 13:53:00'),
(229, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:00', '2023-10-17 13:53:00'),
(230, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:02', '2023-10-17 13:53:02'),
(231, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:03', '2023-10-17 13:53:03'),
(232, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:04', '2023-10-17 13:53:04'),
(233, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:06', '2023-10-17 13:53:06'),
(234, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:07', '2023-10-17 13:53:07'),
(235, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:08', '2023-10-17 13:53:08'),
(236, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:09', '2023-10-17 13:53:09'),
(237, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:11', '2023-10-17 13:53:11'),
(238, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:12', '2023-10-17 13:53:12'),
(239, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:13', '2023-10-17 13:53:13'),
(240, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:15', '2023-10-17 13:53:15'),
(241, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:16', '2023-10-17 13:53:16'),
(242, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:17', '2023-10-17 13:53:17'),
(243, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:19', '2023-10-17 13:53:19'),
(244, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:20', '2023-10-17 13:53:20'),
(245, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:21', '2023-10-17 13:53:21'),
(246, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:23', '2023-10-17 13:53:23'),
(247, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:24', '2023-10-17 13:53:24'),
(248, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:25', '2023-10-17 13:53:25'),
(249, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:27', '2023-10-17 13:53:27'),
(250, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:28', '2023-10-17 13:53:28'),
(251, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:29', '2023-10-17 13:53:29'),
(252, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:31', '2023-10-17 13:53:31'),
(253, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:32', '2023-10-17 13:53:32'),
(254, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:33', '2023-10-17 13:53:33'),
(255, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:35', '2023-10-17 13:53:35'),
(256, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:36', '2023-10-17 13:53:36'),
(257, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:37', '2023-10-17 13:53:37'),
(258, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:38', '2023-10-17 13:53:38'),
(259, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:40', '2023-10-17 13:53:40'),
(260, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:41', '2023-10-17 13:53:41'),
(261, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:42', '2023-10-17 13:53:42'),
(262, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:44', '2023-10-17 13:53:44'),
(263, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:45', '2023-10-17 13:53:45'),
(264, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:46', '2023-10-17 13:53:46'),
(265, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:48', '2023-10-17 13:53:48'),
(266, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:49', '2023-10-17 13:53:49'),
(267, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:50', '2023-10-17 13:53:50'),
(268, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:52', '2023-10-17 13:53:52'),
(269, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:53', '2023-10-17 13:53:53'),
(270, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:54', '2023-10-17 13:53:54'),
(271, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:56', '2023-10-17 13:53:56'),
(272, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:57', '2023-10-17 13:53:57'),
(273, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:53:58', '2023-10-17 13:53:58'),
(274, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:00', '2023-10-17 13:54:00'),
(275, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:01', '2023-10-17 13:54:01'),
(276, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:02', '2023-10-17 13:54:02'),
(277, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:04', '2023-10-17 13:54:04'),
(278, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:05', '2023-10-17 13:54:05'),
(279, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:06', '2023-10-17 13:54:06'),
(280, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:08', '2023-10-17 13:54:08'),
(281, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:09', '2023-10-17 13:54:09'),
(282, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:10', '2023-10-17 13:54:10'),
(283, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:12', '2023-10-17 13:54:12'),
(284, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:13', '2023-10-17 13:54:13'),
(285, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:14', '2023-10-17 13:54:14'),
(286, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:15', '2023-10-17 13:54:15'),
(287, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:17', '2023-10-17 13:54:17'),
(288, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:18', '2023-10-17 13:54:18'),
(289, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:19', '2023-10-17 13:54:19'),
(290, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:20', '2023-10-17 13:54:20'),
(291, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:21', '2023-10-17 13:54:21'),
(292, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:23', '2023-10-17 13:54:23'),
(293, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:24', '2023-10-17 13:54:24'),
(294, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:25', '2023-10-17 13:54:25'),
(295, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:26', '2023-10-17 13:54:26'),
(296, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:28', '2023-10-17 13:54:28'),
(297, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:29', '2023-10-17 13:54:29'),
(298, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:30', '2023-10-17 13:54:30'),
(299, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:31', '2023-10-17 13:54:31'),
(300, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:33', '2023-10-17 13:54:33'),
(301, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:34', '2023-10-17 13:54:34'),
(302, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:35', '2023-10-17 13:54:35'),
(303, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:36', '2023-10-17 13:54:36'),
(304, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:38', '2023-10-17 13:54:38'),
(305, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:39', '2023-10-17 13:54:39'),
(306, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:40', '2023-10-17 13:54:40'),
(307, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:41', '2023-10-17 13:54:41'),
(308, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:43', '2023-10-17 13:54:43'),
(309, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:44', '2023-10-17 13:54:44'),
(310, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:45', '2023-10-17 13:54:45'),
(311, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:46', '2023-10-17 13:54:46'),
(312, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:48', '2023-10-17 13:54:48'),
(313, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:49', '2023-10-17 13:54:49'),
(314, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:50', '2023-10-17 13:54:50'),
(315, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:51', '2023-10-17 13:54:51'),
(316, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:53', '2023-10-17 13:54:53'),
(317, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:54', '2023-10-17 13:54:54'),
(318, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:55', '2023-10-17 13:54:55'),
(319, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:56', '2023-10-17 13:54:56'),
(320, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:58', '2023-10-17 13:54:58'),
(321, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:54:59', '2023-10-17 13:54:59'),
(322, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:00', '2023-10-17 13:55:00'),
(323, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:02', '2023-10-17 13:55:02'),
(324, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:03', '2023-10-17 13:55:03'),
(325, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:04', '2023-10-17 13:55:04'),
(326, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:05', '2023-10-17 13:55:05'),
(327, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:06', '2023-10-17 13:55:06'),
(328, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:08', '2023-10-17 13:55:08'),
(329, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:09', '2023-10-17 13:55:09'),
(330, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:10', '2023-10-17 13:55:10'),
(331, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:11', '2023-10-17 13:55:11'),
(332, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:13', '2023-10-17 13:55:13'),
(333, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:14', '2023-10-17 13:55:14'),
(334, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:15', '2023-10-17 13:55:15'),
(335, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:16', '2023-10-17 13:55:16'),
(336, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:18', '2023-10-17 13:55:18'),
(337, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:19', '2023-10-17 13:55:19'),
(338, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:20', '2023-10-17 13:55:20'),
(339, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:21', '2023-10-17 13:55:21'),
(340, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:23', '2023-10-17 13:55:23'),
(341, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:24', '2023-10-17 13:55:24'),
(342, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:25', '2023-10-17 13:55:25'),
(343, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:26', '2023-10-17 13:55:26'),
(344, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:28', '2023-10-17 13:55:28'),
(345, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:29', '2023-10-17 13:55:29'),
(346, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:30', '2023-10-17 13:55:30'),
(347, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:31', '2023-10-17 13:55:31'),
(348, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:33', '2023-10-17 13:55:33'),
(349, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:34', '2023-10-17 13:55:34'),
(350, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:35', '2023-10-17 13:55:35'),
(351, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:36', '2023-10-17 13:55:36'),
(352, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:38', '2023-10-17 13:55:38'),
(353, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:39', '2023-10-17 13:55:39'),
(354, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:40', '2023-10-17 13:55:40'),
(355, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:41', '2023-10-17 13:55:41'),
(356, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:43', '2023-10-17 13:55:43'),
(357, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:44', '2023-10-17 13:55:44'),
(358, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:45', '2023-10-17 13:55:45'),
(359, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:46', '2023-10-17 13:55:46'),
(360, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:48', '2023-10-17 13:55:48'),
(361, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:49', '2023-10-17 13:55:49'),
(362, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:50', '2023-10-17 13:55:50'),
(363, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:52', '2023-10-17 13:55:52'),
(364, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:53', '2023-10-17 13:55:53'),
(365, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:54', '2023-10-17 13:55:54'),
(366, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:55', '2023-10-17 13:55:55'),
(367, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:57', '2023-10-17 13:55:57'),
(368, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:58', '2023-10-17 13:55:58'),
(369, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:55:59', '2023-10-17 13:55:59'),
(370, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:01', '2023-10-17 13:56:01'),
(371, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:02', '2023-10-17 13:56:02'),
(372, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:03', '2023-10-17 13:56:03'),
(373, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:04', '2023-10-17 13:56:04'),
(374, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:06', '2023-10-17 13:56:06'),
(375, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:07', '2023-10-17 13:56:07'),
(376, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:08', '2023-10-17 13:56:08'),
(377, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:09', '2023-10-17 13:56:09'),
(378, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:11', '2023-10-17 13:56:11'),
(379, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:12', '2023-10-17 13:56:12'),
(380, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:13', '2023-10-17 13:56:13'),
(381, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:15', '2023-10-17 13:56:15'),
(382, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:16', '2023-10-17 13:56:16'),
(383, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:17', '2023-10-17 13:56:17'),
(384, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:18', '2023-10-17 13:56:18'),
(385, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:20', '2023-10-17 13:56:20'),
(386, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:21', '2023-10-17 13:56:21'),
(387, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:22', '2023-10-17 13:56:22'),
(388, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:24', '2023-10-17 13:56:24'),
(389, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:25', '2023-10-17 13:56:25'),
(390, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:26', '2023-10-17 13:56:26'),
(391, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:27', '2023-10-17 13:56:27'),
(392, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:29', '2023-10-17 13:56:29'),
(393, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:30', '2023-10-17 13:56:30'),
(394, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:31', '2023-10-17 13:56:31'),
(395, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:33', '2023-10-17 13:56:33'),
(396, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:37', '2023-10-17 13:56:37');
INSERT INTO `payments` (`id`, `email`, `orderiD`, `amount`, `currency`, `reference`, `created_at`, `updated_at`) VALUES
(397, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:39', '2023-10-17 13:56:39'),
(398, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:40', '2023-10-17 13:56:40'),
(399, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:41', '2023-10-17 13:56:41'),
(400, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:42', '2023-10-17 13:56:42'),
(401, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:44', '2023-10-17 13:56:44'),
(402, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:45', '2023-10-17 13:56:45'),
(403, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:46', '2023-10-17 13:56:46'),
(404, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:48', '2023-10-17 13:56:48'),
(405, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:49', '2023-10-17 13:56:49'),
(406, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:50', '2023-10-17 13:56:50'),
(407, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:51', '2023-10-17 13:56:51'),
(408, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:53', '2023-10-17 13:56:53'),
(409, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:54', '2023-10-17 13:56:54'),
(410, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:55', '2023-10-17 13:56:55'),
(411, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:57', '2023-10-17 13:56:57'),
(412, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:56:58', '2023-10-17 13:56:58'),
(413, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:00', '2023-10-17 13:57:00'),
(414, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:01', '2023-10-17 13:57:01'),
(415, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:02', '2023-10-17 13:57:02'),
(416, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:03', '2023-10-17 13:57:03'),
(417, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:04', '2023-10-17 13:57:04'),
(418, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:08', '2023-10-17 13:57:08'),
(419, 'abidemi@gmail.com', '144591298', 1000, 'GHS', 'SQyh7ZJtuebybFl7J23bQ6Cz2', '2023-10-17 13:57:11', '2023-10-17 13:57:11'),
(420, 'yawo@gmail.com', '144793374', 1000, 'GHS', 'rvoTPtBzn9YQZeqZ4PZzK6Tqu', '2023-10-19 08:56:53', '2023-10-19 08:56:53');

-- --------------------------------------------------------

--
-- Table structure for table `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `token` varchar(64) NOT NULL,
  `abilities` text DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `personal_access_tokens`
--

INSERT INTO `personal_access_tokens` (`id`, `tokenable_type`, `tokenable_id`, `name`, `token`, `abilities`, `last_used_at`, `created_at`, `updated_at`) VALUES
(1, 'App\\Models\\User', 2, 'password_change_token', 'cde8d607ec9938a29c0f342d1bd8a7ce41658237c05108d79e05f814b074d17f', '[\"*\"]', NULL, '2023-09-03 04:22:22', '2023-09-03 04:22:22'),
(2, 'App\\Models\\User', 2, 'password_change_token', '3c803625161255b81293041b358c0bd15e679a5909d68ef827a6129a144e1a2f', '[\"*\"]', NULL, '2023-09-03 04:23:19', '2023-09-03 04:23:19'),
(3, 'App\\Models\\User', 2, 'password_change_token', '0f3b09dc76d23284f061f7ef84e9f01f12a76a2909923f0d2d837960910d007e', '[\"*\"]', NULL, '2023-09-03 04:23:49', '2023-09-03 04:23:49'),
(4, 'App\\Models\\User', 2, 'password_change_token', '0b334cce30d3465ff8539a10098a911de2634ae9398310bda1e612f80e97ed97', '[\"*\"]', NULL, '2023-09-03 04:26:10', '2023-09-03 04:26:10'),
(5, 'App\\Models\\User', 2, 'password_change_token', '098518b66ef9e3e8b325819f7dce552bb8c43c8f7918d57e290cfaf04ff8e5a9', '[\"*\"]', NULL, '2023-09-03 04:26:28', '2023-09-03 04:26:28');

-- --------------------------------------------------------

--
-- Table structure for table `profiles`
--

CREATE TABLE `profiles` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) NOT NULL,
  `firstName` varchar(255) NOT NULL,
  `lastName` varchar(255) NOT NULL,
  `profilePicture` varchar(255) NOT NULL,
  `tagOne` varchar(255) NOT NULL,
  `tagTwo` varchar(255) NOT NULL,
  `tagThree` varchar(255) NOT NULL,
  `telephoneNo` varchar(255) NOT NULL,
  `dateOfBirth` date NOT NULL,
  `gender` varchar(255) NOT NULL,
  `sexualOrientation` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `town` varchar(255) NOT NULL,
  `socialOne` varchar(255) NOT NULL,
  `socialTwo` varchar(255) NOT NULL,
  `referal` varchar(255) NOT NULL,
  `noOfReveals` int(11) NOT NULL DEFAULT 0,
  `brandAmbassador` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `activeStatus` varchar(255) NOT NULL DEFAULT 'on'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `profiles`
--

INSERT INTO `profiles` (`id`, `email`, `firstName`, `lastName`, `profilePicture`, `tagOne`, `tagTwo`, `tagThree`, `telephoneNo`, `dateOfBirth`, `gender`, `sexualOrientation`, `city`, `town`, `socialOne`, `socialTwo`, `referal`, `noOfReveals`, `brandAmbassador`, `created_at`, `updated_at`, `activeStatus`) VALUES
(6, 'Kwame@gmail.com', 'Kwame', 'K', 'profilePictures/xVOZTMwy0XXIWAkn6r3Nw8jgEPiFYSPRdzSN08JH.jpg', 'Movie buff', 'Cool', 'Farmer', '(+233) 435 345 0000', '1998-01-07', 'Male', 'Male', 'Kumasi', 'Nhyiaeso', 'insta', 'titkok', 'autogenerated', 1, 'on', '2023-09-07 12:27:47', '2023-10-17 12:07:47', 'on'),
(7, 'Ekow@gmail.com', 'Ekow', 'E', 'profilePictures/Fv2JbxCun4BemefNC2GludcZGqPoSLqXSfr0pRqI.jpg', 'Movie buff', 'Neatfreak', 'Influencer', '(+233) 675 675 6757', '1995-01-18', 'Male', 'Male', 'Accra', 'Airport Residential Area', 'inst', 'tiktok', 'autogenerated', 0, 'on', '2023-09-07 13:02:33', '2023-10-17 12:08:48', 'on'),
(8, 'Yawo@gmail.com', 'Yawo', 'Y', 'profilePictures/7UQBaI8kOdX8LR1x6Gd4eIjYNogmZwxBlJDxE5U5.jpg', 'Snapchatter', 'Neatfreak', 'Entrepreneur', '(+233) 545 645 6456', '1994-02-10', 'Male', 'Male', 'Accra', 'Kokomlemle', 'insta', 'tiktok', 'autogenerated', 0, 'on', '2023-09-07 13:04:41', '2023-10-17 12:09:58', 'on'),
(9, 'Yaa@gmail.com', 'Yaa', 'y', 'profilePictures/2bXkNioHyjUv3PvGQC9KmTqIlpqdyTpl2oAxmkhc.jpg', 'Movie buff', 'Freedom Fighter', 'Entrepreneur', '(+233) 757 575 6756', '1996-07-26', 'Female', 'Female', 'Accra', 'Accra New Town', 'insta', 'tiktok', 'autogenerated', 11, 'on', '2023-09-07 13:07:01', '2023-10-17 12:10:32', 'on'),
(15, 'haiderhamdani1996@gmail.com', 'Ali', 'Haider', 'profilePictures/AdZZ7aLl2uYEk2L3aLIAtnc5b4qhCCSc5tIyq6AX.jpg', 'Creative', 'Freedom Fighter', 'Professional', '(+233) 231 312 3123', '2007-08-29', 'Male', 'Male', 'Accra', 'Tesano', '123123', '12312321', 'autogenerated', 28, 'on', '2023-09-26 11:52:56', '2023-11-20 13:45:30', 'on'),
(16, 'justofosu@gmail.com', 'Derrick', 'Lucas', 'profilePictures/X6YBHqjEXojap34qpeLYssl5jCP1fjJMVMUPO5Oe.png', 'Creative', 'Political Enthusiast', 'Event Planner', '(+233) 055 227 9090', '1963-09-21', 'Male', 'Male', 'Accra', 'Cantoment', '/ghanaone', '/ghanaobe', 'autogenerated', 0, 'on', '2023-09-28 15:05:21', '2023-12-21 16:56:44', 'on'),
(17, 'efoaccra@gmail.com', 'Derrick', 'Lucas', 'profilePictures/LLXRLR3yskVYtaa0NBvtNDRAHWUwYQMtNT6nUvh1.png', 'Foodie', 'Neatfreak', 'Event Planner', '(+233) 079 034 4099', '2004-06-25', 'Male', 'Female', 'Kumasi', 'Patasi', '/ghanaone', '/ghanaobe', 'autogenerated', 0, 'on', '2023-10-06 18:07:59', '2023-10-06 18:07:59', 'on'),
(18, 'Adisa@gmail.com', 'Adisa', 'A', 'profilePictures/44AuIAj3riR8JUKd2J6qiNJ3n9mJU5MjerWurICE.jpg', 'Movie buff', 'Neatfreak', 'Entrepreneur', '(+233) 435 345 3453', '2007-05-30', 'Male', 'Male', 'Accra', 'Ashaiman', '/Adisa', '/Adisa', 'autogenerated', 0, NULL, '2023-10-17 13:38:23', '2023-10-17 13:38:23', 'on'),
(19, 'Jelani@gmail.com', 'Jelani', 'J', 'profilePictures/K85VBRb6MT4R93xh6J2IwGMEZmwGLYlNoX1iIJEf.jpg', 'Explorer', 'Girly', 'Entrepreneur', '(+233) 432 423 4234', '2007-10-02', 'Male', 'Male', 'Accra', 'Accra New Town', '/Jelani', '/Jelani', 'autogenerated', 0, NULL, '2023-10-17 13:42:03', '2023-10-17 13:42:03', 'on'),
(20, 'Abidemi@gmail.com', 'Abidemi', 'A', 'profilePictures/D5Aq24qqGFGpNtJGKgVsVe03GMoDDny8lQWQrlFW.jpg', 'Movie buff', 'Unsociable', 'Designer', '(+233) 424 234 2342', '2007-10-09', 'Male', 'Male', 'Accra', 'Sakumono', '/Abidemi', '/Abidemi', 'autogenerated', 0, NULL, '2023-10-17 13:46:14', '2023-10-17 13:46:14', 'on'),
(21, 'sad@gmail.com', 'adsa', 'sadasd', 'profilePictures/LtSzdUpPIfoAFJZ3xCULTWMrxESGObnugFEhcXP7.png', 'Explorer', 'Religious', 'Make up Artis', '(+233) 343 243 2423', '2007-11-09', 'Male', 'Female', 'Kumasi', 'Kejetia Market', 'asdsad', 'asdasdsa', 'autogenerated', 0, NULL, '2023-11-14 17:27:08', '2023-11-14 17:27:08', 'on'),
(22, 'haiderhamdani95@gmail.com', 'asda', 'asdasd', 'profilePictures/OilpOILi5rmpc8F98oNuXeUcqTfMrdJraChgpB5m.png', 'Sportfan', 'Neatfreak', 'Entrepreneur', '(+233) 243 243 2432', '2007-11-29', 'Male', 'Female', 'Accra', 'Accra New Town', 'asdsa', 'dsad', 'autogenerated', 0, NULL, '2023-12-04 18:28:28', '2023-12-04 18:28:28', 'on');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `email` varchar(255) NOT NULL,
  `userType` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `admin_verification_status` varchar(255) DEFAULT NULL,
  `restriction_status` varchar(255) DEFAULT NULL,
  `date_of_restriction` timestamp NULL DEFAULT NULL,
  `restriction_days` int(11) DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `userType`, `email_verified_at`, `password`, `admin_verification_status`, `restriction_status`, `date_of_restriction`, `restriction_days`, `remember_token`, `created_at`, `updated_at`) VALUES
(7, 'Kwame@gmail.com', 'lessor', NULL, '$2y$10$t1h/vWrEpZBISps5E3jx/uJvKZQf4RhA1ASicTPU/8UaxMGoIMhM.', '', '', '0000-00-00 00:00:00', 0, 'ryEXy5iaAS8xM9lFOd6UXqPSM9Xs4ERRq6keepzUOnnOoF2ixUBw9XbH9zgO', '2023-09-07 12:21:26', '2023-09-23 18:09:49'),
(8, 'Ekow@gmail.com', 'lessor', NULL, '$2y$10$t1h/vWrEpZBISps5E3jx/uJvKZQf4RhA1ASicTPU/8UaxMGoIMhM.', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-09-07 13:01:44', '2023-09-07 13:01:44'),
(9, 'Yawo@gmail.com', 'lessor', NULL, '$2y$10$t1h/vWrEpZBISps5E3jx/uJvKZQf4RhA1ASicTPU/8UaxMGoIMhM.', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-09-07 13:03:57', '2023-10-19 08:51:24'),
(10, 'Yaa@gmail.com', 'lessee', NULL, '$2y$10$t1h/vWrEpZBISps5E3jx/uJvKZQf4RhA1ASicTPU/8UaxMGoIMhM.', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-09-07 13:06:20', '2023-10-17 12:53:54'),
(16, 'haiderhamdani1996@gmail.com', 'lessor', '2023-12-04 17:45:46', '$2y$10$fTGca8VsoyeRZsgEtbwM9e1s2nEuhBhbp62klhYNYJJDiAc4t.8Ky', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-09-26 11:51:54', '2023-12-04 17:30:29'),
(17, 'justofosu@gmail.com', 'lessor', '2023-12-04 17:45:46', '$2y$10$5RHldpJW9j8ugz2SDgkz.utetstzG3L9AeKpQZ78.WbgWM8cRV6Ha', '', '', '0000-00-00 00:00:00', 0, 'zl750IRo2NbZJBkwT8ERypSS4KNsERFBCrEfg0ieG2SnajYxeXt84pgsAkbU', '2023-09-28 15:03:41', '2023-12-04 17:51:57'),
(18, 'efoaccra@gmail.com', 'lessee', NULL, '$2y$10$f3WmCsfkX8LH9uObUKZjXuOZB6WWfvSZw8pnC.kE7fO.V5Xw/r4L6', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-10-06 18:05:49', '2023-10-06 18:05:49'),
(19, 'Adisa@gmail.com', 'lessor', NULL, '$2y$10$/THA05yXwVE7kjPxlO3fneDMUshh7QmWtYv4tST8D0lkVf/3IHfxO', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-10-17 13:22:56', '2023-10-17 13:22:56'),
(20, 'Jelani@gmail.com', 'lessor', NULL, '$2y$10$P3WG2t7U9USp.8aOt1vSyuKJMZT2d87NJ0EciGWwS4GGGS.jj4p0e', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-10-17 13:41:09', '2023-10-17 13:41:09'),
(21, 'Abidemi@gmail.com', 'lessor', NULL, '$2y$10$omhw9M1kxhVWJwSlXqgTfee.qfpbdKtkdthZS/PWfmiOUcEQkTQmm', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-10-17 13:45:23', '2023-10-17 13:45:23'),
(22, 'tomgstockton@gmail.com', 'lessor', NULL, '$2y$10$WXPCo.Ww0dVS6ZDiJgGs1uJBN/xalKQ3J8VykqZ1N1CANyfmV9Wkm', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-11-09 10:48:07', '2023-11-09 10:48:07'),
(23, 'rosefunerals@outlook.com', 'lessor', NULL, '$2y$10$uqfU6ZbrPF3igbWoKQCpg.NXray79W8QxO.GAJ.XN5TTo6RtjzMJC', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-11-11 21:03:28', '2023-11-11 21:03:28'),
(24, 'sad@gmail.com', 'lessor', NULL, '$2y$10$GjT9ZIlzUDOVG.AUy9ctGeV9/Hm1YaxQooPZUSP5q.iV2RYZcfTve', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-11-14 17:26:35', '2023-11-14 17:26:35'),
(25, 'webaccra57@gmail.com', 'lessor', NULL, '$2y$10$cKVU7IdwJWkU.wDvgXM1sOeB4elqqZm6s/86CLMH7Pm6Q79vBuW7S', '', '', '0000-00-00 00:00:00', 0, 'ySchmsUSMQjTH5fiPAVyovIJiprfK9CqwByOIrcioS0grkwDRbRD16qnQXVU', '2023-11-26 10:38:37', '2023-11-26 10:38:37'),
(26, 'efoaccra1@gmail.com', 'lessor', NULL, '$2y$10$DKQ.7/B3DqUf.gZlWjZRzucxnCTAxruk1bEHhknzJ2QcE9edugjgG', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-11-26 10:48:56', '2023-11-26 10:48:56'),
(27, 'hmLHbj.hddwqpq@flexduck.click', 'lessor', NULL, '$2y$10$CfGbsHQSlt/xkkmIRlRhm.2KLrsOGhpb3XZ04BFkfTmJ00WoAsbSS', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-11-28 20:06:28', '2023-11-28 20:06:28'),
(30, 'haiderhamdani95@gmail.com', 'lessor', '2023-12-04 17:45:46', '$2y$10$.MQiXvezburhBo50z20QNOdnofYAWe2HRZc0l2z5fUsoIZEZ/Xc0S', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-04 17:15:27', '2023-12-04 17:16:01'),
(31, 'JKFMLW.htdpwbp@anaphora.team', 'lessee', NULL, '$2y$10$6o9TttyU/nPca60UBzBb0edyU9GT6OLO1FgNipzKbQPKGVkmSVRAS', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-10 06:16:37', '2023-12-10 06:16:37'),
(32, 'MjjKOt.hwwwtmh@wheelry.boats', 'lessee', NULL, '$2y$10$1PxLC4LfFCSZcVVNc9.KreqZg43B/..Enw2wazK0WxPA7oDsPY5mu', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-11 19:46:07', '2023-12-11 19:46:07'),
(33, 'michelle@hultine.com', 'lessee', NULL, '$2y$10$nGi2FzZNysolWaPQVDHn4.AJLJzMvKnCsGWh3ScZTwAoXjcvivLjO', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-11 19:56:28', '2023-12-11 19:56:28'),
(34, 'heriberto910@gmail.com', 'lessee', NULL, '$2y$10$jgJ/L7h7Mru8rQ6Ek7m3m.kxvZ5tpMRSo3NO/ReYAEFhMsLG2FVsW', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-11 23:09:51', '2023-12-11 23:09:51'),
(35, 'pdilley@stonestreetquarries.com', 'lessee', NULL, '$2y$10$.WIz4PocpU.zk.JTyv7SOOO1gMwMvGEYtVgQyshv.aPQpmX0pRTwy', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-12 02:28:54', '2023-12-12 02:28:54'),
(36, 'zach.fabry@bulkfluidsystems.com', 'lessee', NULL, '$2y$10$ZUqKLGhKcR6LuewtqZeRguf8Y13v8CtVhOEEK9bNwyEbunNI4YHKO', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-12 16:56:55', '2023-12-12 16:56:55'),
(37, 'mesko@meskoglass.biz', 'lessee', NULL, '$2y$10$dxlb2vkglqhkoYhqNto7uOzagwZTShhAaL0qJOxJZekE3x4Pqk1wS', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-12 20:11:57', '2023-12-12 20:11:57'),
(38, 'mdevey@ustservicescorp.com', 'lessee', NULL, '$2y$10$CGkz4TAtVQJtoQ4zpGaEQ.JYZKNEmNEISls16aPzAcJZMlECok/NO', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-13 00:19:31', '2023-12-13 00:19:31'),
(39, 'info@vdefa.nl', 'lessee', NULL, '$2y$10$p9JPFCKr8PE6zykkqitnzeWQ8BnkY07CyaG1wj7pL8Z0SnHbsKQEy', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-13 13:29:35', '2023-12-13 13:29:35'),
(40, 'dawnlandcorp.7@gmail.com', 'lessee', NULL, '$2y$10$Zr.vve3ObgsPhCRE2TEdH.lWMy70VrT0d2pWEFNjLCDxwBOaTjNYu', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-13 15:52:47', '2023-12-13 15:52:47'),
(41, 'silverfox8949@gmail.com', 'lessee', NULL, '$2y$10$QcV2ozpg4fTwjFWbhuPnHefbZyHcIj81/g.ajEBT0A6G9Un8N.Xp.', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-13 18:56:26', '2023-12-13 18:56:26'),
(42, 'info@matteogerbi.com', 'lessee', NULL, '$2y$10$ZKGY9U0JGJ32B0LYFUnEbu0KftTnTlDg90iMF5S8VPr6VkQjzwLRq', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-13 23:12:14', '2023-12-13 23:12:14'),
(43, 'ebaysmith2014@gmail.com', 'lessee', NULL, '$2y$10$rsYrg4MMqoHXqBK9VKBlC.s5pREegpoqAsbNgMC2w6UbvfTbMJNei', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-14 01:56:21', '2023-12-14 01:56:21'),
(44, 'tthomas@ustservicescorp.com', 'lessee', NULL, '$2y$10$fSeUazSM9cyy3J/s5f5h8.HGvX9IwTNxtRDMdCvsu7dfJTwuyUm86', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-14 04:36:43', '2023-12-14 04:36:43'),
(45, 'ifuentes@cfhgroup.com', 'lessee', NULL, '$2y$10$3JwYJmlTy3UiqAPkt6Wfne.RINvbpmX1kkSqVgl28kqcOJM2A3eYu', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-14 13:05:06', '2023-12-14 13:05:06'),
(46, 'ian.roy.schaffer@gmail.com', 'lessee', NULL, '$2y$10$APQF2jTgT0wxMVyjN/mJvOJVWoCurem34ACfSkbiL5N/h.zBvPn9m', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-14 14:47:39', '2023-12-14 14:47:39'),
(47, 'pinefieldecofarm@gmail.com', 'lessee', NULL, '$2y$10$9vLVSMcejRH7lGkHFSncluYpy.fG0TLlwF5DppcuJyIUi35gHjwfG', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-14 16:58:41', '2023-12-14 16:58:41'),
(48, 'joe_bet@aol.com', 'lessee', NULL, '$2y$10$XE8fwcoc8S.df8aT9wHuZu0ju4r6TwXVINbRObUN5ua/Y6xXWu5uC', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-14 20:05:52', '2023-12-14 20:05:52'),
(49, 'cWqpXy.qdmq@rightbliss.beauty', 'lessee', NULL, '$2y$10$/f0zWxR1jGduxxj/nLqD6ejL/wgwr0DrYDIj8DUFJao6tAgZ4QPyi', '', '', '0000-00-00 00:00:00', 0, NULL, '2023-12-23 03:13:59', '2023-12-23 03:13:59'),
(51, 'AUjLet.pmphmj@tarboosh.shop', 'lessee', NULL, '$2y$10$HNRf90Fwlgb2qYYUj.ENcOoykTnOT.7HUbVNW49T8I7JK5ywtZWqG', NULL, NULL, NULL, NULL, NULL, '2023-12-30 00:44:27', '2023-12-30 00:44:27'),
(52, 'rramos@taconiccap.com', 'lessee', NULL, '$2y$10$F9QnkGEjhiZQQef865oT5OVTaYAahDpUOCEuXv0pKqNgnn0TP9r72', NULL, NULL, NULL, NULL, NULL, '2023-12-30 00:57:33', '2023-12-30 00:57:33');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indexes for table `list_rooms`
--
ALTER TABLE `list_rooms`
  ADD PRIMARY KEY (`id`),
  ADD KEY `list_rooms_email_foreign` (`email`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `payments`
--
ALTER TABLE `payments`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indexes for table `profiles`
--
ALTER TABLE `profiles`
  ADD PRIMARY KEY (`id`),
  ADD KEY `profiles_email_foreign` (`email`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `list_rooms`
--
ALTER TABLE `list_rooms`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT for table `payments`
--
ALTER TABLE `payments`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=421;

--
-- AUTO_INCREMENT for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `profiles`
--
ALTER TABLE `profiles`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `list_rooms`
--
ALTER TABLE `list_rooms`
  ADD CONSTRAINT `list_rooms_email_foreign` FOREIGN KEY (`email`) REFERENCES `users` (`email`);

--
-- Constraints for table `profiles`
--
ALTER TABLE `profiles`
  ADD CONSTRAINT `profiles_email_foreign` FOREIGN KEY (`email`) REFERENCES `users` (`email`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
